---
language: c
os: linux
jobs:
  include:
    # macOS
    - env: TARGET_MACHINE=a6osx
      os: osx
      osx_image: xcode11
    - env: TARGET_MACHINE=a6osx CHEZ_BRANCH=main
      os: osx
      osx_image: xcode11
    - env: TARGET_MACHINE=ta6osx
      os: osx
      osx_image: xcode11

    # Linux
    - env: TARGET_MACHINE=i3le
      os: linux
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - lib32ncurses5-dev
            - libsystemd-dev:i386
            - libx32ncurses5-dev
            - uuid-dev:i386
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
    - env: TARGET_MACHINE=ti3le
      os: linux
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - lib32ncurses5-dev
            - libsystemd-dev:i386
            - libx32ncurses5-dev
            - uuid-dev:i386
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
    - env: TARGET_MACHINE=a6le
      os: linux
      addons:
        apt:
          packages:
            - libsystemd-dev
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
    - env: TARGET_MACHINE=a6le CHEZ_BRANCH=main
      os: linux
      addons:
        apt:
          packages:
            - libsystemd-dev
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
    - env: TARGET_MACHINE=ta6le
      os: linux
      addons:
        apt:
          packages:
            - libsystemd-dev
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0

    # Windows
    - env: TARGET_MACHINE=i3nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=ti3nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=a6nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=a6nt CHEZ_BRANCH=main
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=ta6nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
dist: bionic
script:
  - .travis/get-chez-scheme.sh
  - .travis/build.sh
  - .travis/test.sh
