#!/bin/sh
set -e
if [ -f swish/Makefile ]; then
  make --no-print-directory -C swish ready
else
  echo "Run ./configure in the top-level directory to build src/swish/Makefile"
  exit 1
fi
if [ -z ${SCHEME+x} ]; then SCHEME=scheme; fi
"${SCHEME}" --eedisable --program repl.ss "$@"
