#!/bin/sh -e
if [ -z ${SCHEME+x} ]; then SCHEME=scheme; fi
if [ ${LAUNCH+X} ]; then
  prog="${LAUNCH}"
else
  prog="${SCHEME} --eedisable -q replp.ss run-mats.ss"
fi
launch() {
  PROFILE_MATS="yes" ${prog}
}

if [ $# != 1 ]; then
  echo "Usage: $0 suite"
  exit
fi

find . -name "*.mo" -delete
find . -name "*.html" -and -not -iwholename "*/web-mats/*" -delete
rm -f ../data/server.profile
rm -f ../data/TestLog.db3
make -s -C swish

launch <<EOF
(run-suite "$1" ".")
EOF

# finish up
launch <<EOF
(html-report "." "suite-report.html")
(console-summary ".")
EOF

./dump-profile $bits
