#!/bin/sh -e

if [ $# = 0 ]; then
  echo "Usage: $0 [-b] suite [test ...]"
  echo ""
  echo " For example:"
  echo "   $0 swish/json"
  echo "   $0 swish/json read errors"
  echo "   $0 swish/json.ms"
  echo "   $0 swish/profile.ss"
  echo "   $0 swish/erlang chain-reaction"
  echo ""
  echo " -b  means build mat-prereq and use that to run test"
  exit
fi

BUILD=0
RUN=./go

if [ "$1" = '-b' ]; then
  shift;
  BUILD=1
  RUN=../build/mat-prereq/bin/swish
fi

find . -name "*.mo" -delete
rm -f ../data/server.profile
rm -f ../data/TestLog.db3
if [ ${BUILD} -eq 0 ]; then
  make -s -C swish
else
  make -s -C swish mat-prereq
fi

FILENAME="$1"
if [ ! -f "${FILENAME}" ]; then
  FILENAME="$1.ms"
fi

shift

${RUN} -q <<EOF
(reset-handler abort)
(import (swish mat) (swish profile) (swish testing))
(cd "..")
(\$init-mat-output-file "src/${FILENAME}.mo" "src/${FILENAME}" (uuid->string (osi_make_uuid)))
(\$run-test-spec
  (<test-spec> make
    [test-file "src/${FILENAME}"]
    [test-run (osi_make_uuid)]
    [report-file "src/${FILENAME}.mo"]
    [tests
     (let ([tests (map string->symbol (remq "" (split "$@" #\space)))])
       (and (pair? tests) tests))]
    [incl-tags '()]
    [excl-tags '()]
    [profile
     (and (equal? (getenv "PROFILE_MATS") "yes")
          (let ([filename (path-combine "src" "${FILENAME}.profile")])
            (close-port (open-file-to-replace filename))
            filename))]
    [progress 'test]
    [lib-dirs '("src" ".")]
    [src-dirs '("src" ".")]))
EOF
