#!/bin/sh -e

if [ $# != 1 ]; then
  echo "Usage: $0 suite"
  exit
fi

cd "$(git rev-parse --show-toplevel)"

SUITE="src/$1"
if [ ! -f "${SUITE}" ]; then
  SUITE="${SUITE}.ms"
fi

if [ ! -f "${SUITE}" ]; then
  echo "cannot find suite $1"
  exit 1
fi

make --no-print-directory -C src/swish mat-prereq
src/run-mats "${SUITE}"
