#!/bin/sh -e
# Usage: ./run-mats
#     or ./run-mats bin-path
#
# If bin-path is absent or is ../bin, clean and run tests against code
# in this repository.  Otherwise run the code installed at bin-path
# against the tests in this repository.

if [ -z ${SCHEME+x} ]; then SCHEME=scheme; fi

if [ "$PROFILE_MATS" = "yes" ]; then
  rm -f ../data/server.profile
fi

if [ "$OUTDIR" != "" ]; then
    outdir=$OUTDIR
else
    outdir=.
fi

rm -f ../data/TestLog.db3

if [ ${1+x} ]; then
  if [ ! -d "${1}" ]; then
    echo "$1 is not a directory"
    exit 1
  elif [ "$1" = "../bin" ]; then
    make -C swish clean all
  fi
  PATH=${1}:${PATH}
  launch="../bin/swish-mat"
else
  make -C swish clean ready
  launch="./go -q -- run-mats.ss"
fi

# Swish
source swish/run-mats

# finish up
$launch <<EOF
(html-report "$outdir" "$outdir/mat-report.html")
(console-summary "$outdir")
EOF

if [ "$PROFILE_MATS" != "no" ]; then
  ./dump-profile
fi
